application: varfuri
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /dropshadow
  static_dir: img/dropshadow
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico
- url: /google4b899b9e0462f0cd\.html
  static_files: templates/google4b899b9e0462f0cd.html
  upload: templates/google4b899b9e0462f0cd\.html
- url: /.*
  script: _go_app
  
