runtime: go113

handlers:
- url: /
  static_files: app/base.html
  upload: app/base.html
- url: /css
  static_dir: app/css
- url: /img
  static_dir: app/img
- url: /js
  static_dir: app/js
- url: /lib
  static_dir: app/lib
- url: /partials
  static_dir: app/partials
- url: /dropshadow
  static_dir: app/img/dropshadow
- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon\.ico
- url: /google4b899b9e0462f0cd\.html
  static_files: app/google4b899b9e0462f0cd.html
  upload: app/google4b899b9e0462f0cd\.html
- url: /api/.*
  script: auto
